#bootstrap.yml 是系统级别的，加载优先级高于 application.yml ，负责从外部加载配置并解析
server:
  port: 8001 #端口号
spring:
  config:
    import: "optional:configserver:http://desk-cloud-config-server"
  application:
    name: desk-cloud-modules-system #服务名
  cloud:
    config:
      label: master #分支名称
      name: ${spring.application.name}  #配置文件名称，desk-cloud-gateway-dev.yml 中的 config
      profile: dev  #环境名  desk-cloud-gateway-dev.yml 中的 dev
      #这里不要忘记添加 http:// 否则无法读取
      uri: http://desk-cloud-config-serve #Spring Cloud Config 服务端（配置中心）地址
      discovery:
        enabled: true
        service-id: desk-cloud-config-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/desk_cloud?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: create
    show-sql: true
eureka:
  client: #将客户端注册到 eureka 服务列表内
    service-url:
      defaultZone: http://localhost:7001/eureka/