server:
  port: 3344 #端口号
spring:
  application:
    name: desk-cloud-config-server #服务名
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/lonelymoon1314/desk-cloud-config-server.git
          #仓库名
          search-paths:
            - desk-cloud-config-server
          force-pull: true
          defaultLabel: master
      #分支名
      label: master
eureka:
  client: #将客户端注册到 eureka 服务列表内
    service-url:
      defaultZone: http://localhost:7001/eureka/  #将服务注册到 Eureka 集群 多个服务以逗号隔开