#bootstrap.yml 是系统级别的，加载优先级高于 application.yml ，负责从外部加载配置并解析
server:
  port: 8003 #端口号
spring:
  config:
    import: "optional:configserver:http://desk-cloud-config-server"
  application:
    name: desk-cloud-auth-server #服务名
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: root
    lettuce:
      pool:
        # 连接池中的最大空闲连接 默认8
        max-idle: 8
        # 连接池中的最小空闲连接 默认0
        min-idle: 0
        # 连接池最大连接数 默认8 ，负数表示没有限制
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认-1
        max-wait: -1
    timeout: 30000
  cloud:
    config:
      label: master #分支名称
      name: ${spring.application.name}  #配置文件名称，desk-cloud-gateway-dev.yml 中的 config
      profile: dev  #环境名  desk-cloud-gateway-dev.yml 中的 dev
      #这里不要忘记添加 http:// 否则无法读取
      uri: http://desk-cloud-config-server #Spring Cloud Config 服务端（配置中心）地址
      discovery:
        enabled: true
        service-id: desk-cloud-config-server
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/desk_cloud?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: root
eureka:
  client: #将客户端注册到 eureka 服务列表内
    service-url:
      defaultZone: http://localhost:7001/eureka/
    fetch-registry: true  #服务消费者客户端需要去检索服务